camunda:
  bpm:
    admin-user:
      id: admin
      email: admin@localhost
      first-name: Adminus
      last-name: Administratus
      password: admin
    login:
      enabled: true
      user-id: admin
