server:
  port: 8081

zeebe:
  client:
    cloud:
      region: ${ZEEBE_REGION}
      clusterId: ${ZEEBE_CLUSTER_ID}
      clientId: ${ZEEBE_CLIENT_ID}
      clientSecret: ${ZEEBE_CLIENT_SECRET}

tasklist:
  url: https://${zeebe.client.cloud.region}.tasklist.camunda.io/${zeebe.client.cloud.clusterId}/graphql

operate:
  url: https://${zeebe.client.cloud.region}.operate.camunda.io/${zeebe.client.cloud.clusterId}

